### ISSUE TITLE
Error StripeDateTimeConverter.ReadJson while parsing timestamp with dot

### ISSUE THREAD

**Issue by mvolodin** [jaymedavis/stripe.net#863] opened 2017-05-04 09:40 UTC
Received following errors while using Mapper.MapFromJson with received webhook event from stripe
``` 
Message: 
    String was not recognized as a valid DateTime.

Stack Trace: 
    at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
    at Stripe.Infrastructure.StripeDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
...
```
It looks like datetime converter fails to parse timestamp in following format ```"date": 1493884202.8321862``` (example field from failed event) with the dot in the middle. With other date it was fine.

**Comment by jaymedavis** [comment] 2017-05-04 14:34
I didn't even know epoch dates could contain dots. What field is this?

**Comment by mvolodin** [comment] 2017-05-04 14:38
Me also, 'date' field, transfer.created payload example:
```
{
  "id": "tr_***",
  "object": "transfer",
  "amount": 35600,
  "amount_reversed": 0,
  "balance_transaction": "***",
  "created": 1493883737,
  "currency": "eur",
  "destination": "acct_*",
  "destination_payment": "py_***",
  "livemode": true,
  "metadata": {},
  "reversals": {
    "object": "list",
    "data": [],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/transfers/tr_*/reversals"
  },
  "reversed": false,
  "source_type": "card",
  "transfer_group": "group_ch_**",
  "date": 1493883737.7716506,
  "status": "paid",
  "type": "stripe_account",
  "method": "standard",
  "description": null,
  "failure_message": null,
  "failure_code": null,
  "statement_descriptor": null,
  "recipient": null,
  "source_transaction": "ch_****",
  "application_fee": null
}
```

**Comment by carlosboeing** [comment] 2017-05-08 13:54
We had the same issue. Apparently, this was a bug on Stripe side. We have contacted Stripe and got this reply from them:

> From 05/03 23:41 UTC to 05/04 09:15 UTC, there was a bug on our end where some users started receiving floating point values instead of integer values for the `date` property on transfer objects (for internal transfers only, i.e. transfers between Stripe accounts, not payouts from a Stripe account to a bank account).
>
> This caused an issue with our Java library that prevented the returned transfer objects from being decoded, as the library expects an integer and not a float for the `date` property. While Stripe.net is not an official library, it's very likely that it was similarly affected by this issue.
>
> If you created transfers during that period, note that the transfers were successfully created and processed on Stripe's end. The error happened client-side, when the library tried to decode the incorrectly formatted transfer object returned by the API.

**Comment by jaymedavis** [comment] 2017-05-09 01:04
Thanks @carlosboeing.

There is nothing I can do here.... unless that timestamp can have everything after the decimal stripped off and it's correct. I think this would be a terrible hack. Hopefully, this was just a few requests and the issue is fixed now. Thanks for reporting this.

**Closed by jaymedavis** 2017-05-09 01:04 UTC
