### ISSUE TITLE
Compatibility with .Net Core

### ISSUE THREAD

**Issue by vanpyrzericj** [jaymedavis/stripe.net#535] opened 2016-07-03 16:57 UTC
Not sure if this would belong with #435 but when trying to add this package to a .Net Core app I am getting:

_Package Stripe.net 6.3.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0)._

Happy to do any testing/assistance with this, just let me know how I could help.

-EVP

**Comment by jaymedavis** [comment] 2016-07-03 16:59
This shouldn't be the case - are you using NuGet?

**Comment by vanpyrzericj** [comment] 2016-07-03 17:01
Yep I am. Here is the full output:

_Package Stripe.net 6.3.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Stripe.net 6.3.4 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-monoandroid+monotouch+net45+win8+wp8+wpa81+xamarinios+xamarinmac (.NETPortable,Version=v0.0,Profile=net45+wp8+wpa81+win8+MonoAndroid+MonoTouch+Xamarin.iOS+Xamarin.Mac)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0._

**Comment by jaymedavis** [comment] 2016-07-03 17:25
I haven't upgraded VS to version 3 yet - this .net core full release. That may be all it is. Thanks for reporting.

**Comment by jaymedavis** [comment] 2016-07-03 17:26
Are you on Windows or Mac?

**Comment by vanpyrzericj** [comment] 2016-07-03 17:42
I am running VS Update 3 on Windows. Its running .NET Core Tools Preview 2 (14.1.20624.0) as I haven't been able to find any version newer than that. They made a decent amount of changes to the project.json structure for the final release, I'll bet that's what it is, too.

Here is a copy of the project.json file (for the RTM): http://pastebin.com/SE1Ew4Je

Hope this helps!

**Comment by wakawaka54** [comment] 2016-07-04 03:08
Not sure what all has changed from V1.0.0 of .NET Core to now, but I was able to build a .NET Core Web App with stripes.net through NuGet. I am using .NET Core libraries for **version 1.0.0-rc2-3002702**

**Comment by ry8806** [comment] 2016-07-22 08:03
I've just tried adding Stripe.Net 6.3.4 to .NetCore (Console App) RTM and it works fine

@wakawaka54 Have you got the latest VS Tooling Preview installed??
I think (if possible) you may need to upgrade your application to RTM

I echo @vanpyrzericj's comment and think there was a number of changes the .NetCore team made to the project.json structure and also the way PCL libraries are referenced in .NetCore apps too

**Comment by jaymedavis** [comment] 2016-08-05 19:07
Are you still having trouble with this? I cannot duplicate it either... please leave a comment if you got it worked out for the next guy. :)

**Comment by timadamson** [comment] 2016-08-05 22:39
I'm getting the following error on Core 1.0.0 RTM on a web api project that references a .NETStandard 1.6 project that references Stripe.Net:

Package Stripe.net 6.3.6 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Stripe.net 6.3.6 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-monoandroid+monotouch+net45+win8+wp8+wpa81+xamarinios+xamarinmac (.NETPortable,Version=v0.0,Profile=net45+wp8+wpa81+win8+MonoAndroid+MonoTouch+Xamarin.iOS+Xamarin.Mac)

**Comment by timadamson** [comment] 2016-08-05 22:42
Library project.json

`{
  "version": "1.0.0-*",

  "dependencies": {
    "Centric.User.Data": "1.0.0-*",
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "9.0.1",
    "Stripe.net":  "6.3.6"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}`

Webapi project.json
`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      //"type": "platform",
      "version": "1.0.0"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "System.Net.Http": "4.1.0",
    "System.IdentityModel.Tokens.Jwt": "5.0.0",
    "Swashbuckle": "6.0.0-beta9",
    "Centric.User.Crud": "1.0.0-*",
    "Centric.User.Data": "1.0.0-*",
    "Centric.User.Domain": "1.0.0-*"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {}
  },

  "runtimes": {
    "win10-x64": {},
    "ubuntu.14.04": {},
    "debian.8-x64": {}
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm run styles", "npm run scripts" ]
  }
}
`

**Comment by jaymedavis** [comment] 2016-08-06 04:53
pushed a new release tonight - let me know how it goes.

**Comment by timadamson** [comment] 2016-08-06 08:15
Unfortunately still not working:

error: Package Stripe.net 6.4.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Stripe.net 6.4.0 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - portable-net45+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp8+wpa81)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.

At the moment I've got a work around where I've imported the Stripe project into my solution and am referencing it as a project. That works fine.

Hope that's useful,
Tim

**Comment by jaymedavis** [comment] 2016-08-06 16:23
Looks like wild cards in your json might be the cause https://github.com/dotnet/cli/issues/3703

**Comment by vanpyrzericj** [comment] 2016-08-06 16:47
I got it working on my project, and it looks like @timadamson you were having the same problem I was having, so give this a try:

In the project.json file, my file has this listed in the frameworks section:
`"frameworks": {
"netcoreapp1.0": {}
},`

I vaguely remembered reading the ASP.NET Core docs' [migration section](https://docs.asp.net/en/latest/migration/rc2-to-rtm.html) and how it said "you don't need to use the _imports_ section anymore".  So, naturally, I removed all the _imports_ objects that I could find, not realizing that it was mean't only for the tooling section.

So.... Upon adding back the imports for the netcoreapp1.0:
` "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },`

I no longer got the error when trying to add the Stripe.Net package!

Moral: Don't read sections on migrations in the middle of the night when you're too tired to _not_ make assumptions about what the docs actually tell you to do.

Hope this helps anyone else.

**Comment by jaymedavis** [comment] 2016-08-06 17:36
Thanks, @vanpyrzericj! I didn't remember my migration at all for my product - I remember I used winmerge to compare my RC2 json with a new empty RTM project, and merged things over that way. @timadamson - I hope this fixes it. Please let us know so I can close and point others here as well.

**Comment by timadamson** [comment] 2016-08-07 06:18
That's it! Thanks vanpyrzericj.

And thanks @jaymedavis for looking after this project, it's definitely appreciated :)

**Comment by jaymedavis** [comment] 2016-08-07 09:26
Glad it's solved!

**Closed by jaymedavis** 2016-08-07 09:26 UTC
