### ISSUE TITLE
Cannot add AdditionalOwners in when creating Connect account

### ISSUE THREAD

**Issue by kelvt** [jaymedavis/stripe.net#599] opened 2016-09-14 16:44 UTC
There is no way to add additional owners either when creating an account or updating an account

_var account = new StripeAccountUpdateOptions()
           {
                LegalEntity = new StripeAccountLegalEntityOptions
                {
                         AditionalOwners = **NOTAvailable**_

I also cannot find this anywhere in the documentation, or in the source code itself

Thanks

**Comment by ffMathy** [comment] 2016-11-30 05:27
We really need this too.

**Comment by ivivanov** [comment] 2016-12-14 18:03
Can you provide example on how to add AditionalOwner to  stripe managed account

**Comment by jaymedavis** [comment] 2016-12-14 21:57
This is in progress. I'm on vacation and will figure out what the issue is when I return. :)

**Comment by jaymedavis** [comment] 2016-12-16 09:06
This has been fixed. Few kinks I had to work out!

You can find an example of it's usage in [this test](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net.Tests.xUnit/accounts/adding_additional_owners.cs). Everything is supported except for file uploads for the owners right now. I'm going to punt on that unless it is needed right now - there's lots of other things to get to. 

Let me know if you have trouble!

**Comment by ivivanov** [comment] 2016-12-16 15:14
hey thanks for the fast update! 
btw i noticed that for DOB in StripeAccountAdditionalOwner you are using nullable int but in StripeAccountLegalEntityOptions its string. Is it on purpose?

Also there is strange behavior of stripe when you try to update/delete additional owners. The only work around which works for now is to send nulls and empty string for the ones which you want to delete and just overwrite the existing ones. 

And there is a BUG with the Country field in additional owner. For some reason stripe stores the country from LegalEntity in the additional owner.

**Comment by jaymedavis** [comment] 2016-12-16 23:11
Good catch @ivivanov! Released as 6.13.0 for the StripeAccountLegalEntityOptions fix.

As far as the country field, I would rather leave this issue open and contact Stripe. If this is in fact a bug on their part, they will probably want to fix it.

**Closed** 2016-12-17 21:39 UTC
