### ISSUE TITLE
Swashbuckle error for same JsonProperty

### ISSUE THREAD

**Issue by shribits** [jaymedavis/stripe.net#791] opened 2017-03-20 06:12 UTC
Hi,
In this class StripeAccountSharedOptions there are two properties with the same name for the json property.

 **[JsonProperty("external_account")]**
        public StripeAccountCardOptions ExternalCardAccount { get; set; }
**[JsonProperty("external_account")]**
        public StripeAccountBankAccountOptions ExternalBankAccount { get; set; }

This is resulting in this error:
"500 : {"Message":"An error has occurred.","ExceptionMessage":"A member with the name 'external_account' already exists on "

**Comment by jaymedavis** [comment] 2017-03-27 22:27
This is a known issue for now. What are you trying to do? Are you familiar with StripeResponse?

**Comment by jaymedavis** [comment] 2017-03-27 22:49
dupe of #648

**Closed by jaymedavis** 2017-03-27 22:49 UTC
