### ISSUE TITLE
Fingerprint is null when creating token for card

### ISSUE THREAD

**Issue by descorp** [jaymedavis/stripe.net#447] opened 2016-03-02 12:38 UTC
Fingerprint is null inside token.Card

```
var card = new Card
                {
                    Number = info.Number,
                    ExpiryMonth = info.ExpiryMonth,
                    ExpiryYear = info.ExpiryYear,
                    CVC = info.CVC,
                    Name = info.HolderName
                };

                var token = StripeClient.CreateToken(card).Result;

                return new PaymentConfirm() {Fingerprint = token.Card.Fingerprint, Token = token.Id} ;
```

**Comment by khizar-lango** [comment] 2016-11-02 05:03
Why issue is closed?as fingerprint is coming null from stripe. how can we get valid fingerprint ?

**Comment by jaymedavis** [comment] 2016-11-02 05:17
You closed it :)

**Comment by khizar-lango** [comment] 2016-11-02 05:23
I didn't

**Comment by jaymedavis** [comment] 2016-11-02 05:38
Sorry - the author of the issue did. It's reopened.

**Comment by khizar-lango** [comment] 2016-11-02 05:46
Thanks hope it will be fix soon. i really need it badly

**Comment by jaymedavis** [comment] 2016-11-02 13:49
where are you creating your card from - where do you need the fingerprint available?

**Comment by arslan-lango** [comment] 2016-11-03 16:47
when get the token object using token id after token creation for credit card, sometimes the fingerprint comes null.. so that i am unable to prevent user to add same card multiple times. sometimes fingerprint comes and sometimes it is null. what should i do ?

**Comment by jaymedavis** [comment] 2016-11-05 05:15
Can you share your code? I'm not sure what the issue is here, the original code posted was not Stripe.net. If the fingerprint is sometimes null and sometimes not, it's most likely an issue with Stripe's processing - I would check with them first. Let me know if that doesn't resolve and we can re-open if this is an issue.

**Closed by jaymedavis** 2016-11-05 05:15 UTC

**Comment by JavedAppdevelopment** [comment] 2016-12-14 13:54
Hey, I am getting the same issue.

Here is my code that create a token 

public async Task<CardDetails> TokenizeCardAsync(int expiryMonth, int expiryYear, string cvv,
            string cardRawNameCaptured, CreditCardTokenizeSimulationMode mode, string cardNumber = null)
        {
            bool useLivePublishableKey = cardNumber != null;
            StripeConfiguration.SetApiKey(useLivePublishableKey
                ? _securityManager.StripeLivePublishableKey
                : _securityManager.StripeTestPublishableKey);

            StripeTokenCreateOptions option = new StripeTokenCreateOptions
            {
                Card = new StripeCreditCardOptions
                {
                    Number = cardNumber ?? GetTestCreditCardNumber(mode),
                    ExpirationMonth = expiryMonth.ToString(),
                    ExpirationYear = expiryYear.ToString(),
                    Cvc = cvv,
                    Name = cardRawNameCaptured
                }
            };

            try
            {
                StripeToken token = await new StripeTokenService().CreateAsync(option);

                return new CardDetails
                {
                    CardBrand = token.StripeCard.Brand,
                    CardExpiryMonth = int.Parse(token.StripeCard.ExpirationMonth),
                    CardExpiryYear = int.Parse(token.StripeCard.ExpirationYear),
                    ProviderCardFingerprint = token.StripeCard.Fingerprint,
                    ProviderCardId = token.StripeCard.Id,
                    ProviderToken = token.Id,
                    CardLast4 = token.StripeCard.Last4
                };
            }
            catch (StripeException ex)
            {
                throw new PaymentGatewayException(ex.StripeError.Code, ex.StripeError.Message);
            }
        }

 token.StripeCard.Fingerprint is null.

How can I get the Fingerprint?

please provide solution as early as possible.

Thanks in advance.

**Comment by descorp** [comment] 2016-12-16 19:45
@JavedAppdevelopment in two words - this is how it inplemented by Stripe: fingerprint could be gathered only on server side (using private key). Common scenario is to generate card on server and send to the client.

**Comment by JavedAppdevelopment** [comment] 2016-12-17 05:24
Hey,

Thanks for the reply.

In my case when I creates token, it return null fingerprint.
In Api calling of stripe it return fingerprint, but after start using
stripe.net, I am getting null fingerprint while creates token.

I am confused from your reply likes.

1. Which private key are you talking?
2. can we get fingerprint while create token using stripe.net?
3. if we get fingerprint, does we required another api call?

thanks again for reply.
Javed Kalaniya.
