### ISSUE TITLE
Duplicate [JsonProperty("source")] in StripeChargeCreateOptions

### ISSUE THREAD

**Issue by boraturant** [jaymedavis/stripe.net#716] opened 2017-01-11 10:17 UTC
Duplicate [JsonProperty("source")] in StripeChargeCreateOptions

couses Json serialization error

[JsonProperty("source")]
public string SourceTokenOrExistingSourceId { get; set; }

[JsonProperty("source")]
public SourceCard SourceCard { get; set; }

**Comment by jaymedavis** [comment] 2017-01-11 14:10
Duplicate of #648, see response there and let me know if that helps. Hopefully it eliminates your need to serialize. Comment there if not.

**Closed by jaymedavis** 2017-01-11 14:10 UTC
