### ISSUE TITLE
Using 3DSecure

### ISSUE THREAD

**Issue by sortit-craig** [jaymedavis/stripe.net#861] opened 2017-05-04 08:50 UTC
Hi,

I'm busy implementing Stripe as a payment gateway using Stripe.NET. I'm in the UK, so there are certain cards that need 3DSecure unfortunately.

I have a few questions / issues:

Initially, I wanted to attempt payment using the standard StripeChargeService() and if that failed due to no 3DSecure, then I would proceed to take the user through the 3DSecure process. Unfortunately, Stripe returns a generic failure error on cards that require 3DSecure (using their test cards), so I have no way of telling why it failed.

So on to my other solution: create a customer with card, then use the StripeCardService() to get the status of 3DSecure. However, doing that gives me this:

![image](https://cloud.githubusercontent.com/assets/9465093/25696385/eb8c498a-30ae-11e7-9850-15555e740903.png)

As you can see, the ThreeDSecure property is blank.

I'm using test card 4000000000003063.

I have also tried using the StripeSourceService() instead and process cards as per the Stripe documentation for 3DSecure: https://stripe.com/docs/sources/three-d-secure but StripeSourceCreateOptions() doesn't contain a "card" property.

Am I doing something wrong here? 

Thanks in advance :)

**Comment by sortit-craig** [comment] 2017-05-04 14:50
Ok, so I've managed to figure this out, but not without making some adjustments to Stripe.NET. I'll leave this here in case anyone's having the same issue, or maybe there's another way to do this without changing the library code.

The idea came from how Stripe suggest to handle 3DSecure here: https://stripe.com/docs/sources/three-d-secure - I've adapted something similar using Stripe.NET.

First off, my payment code now starts off by using the StripeSourceService() to create a new source with a type of StripeSourceType.Card. When you do this, Stripe requires a Card object to be passed in the Json of type StripeCreditCardOptions. This lead to modification number 1:

[Services\Sources\StripeSourceCreateOptions.cs](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Services/Sources/StripeSourceCreateOptions.cs) add property:

```
        [JsonProperty("card")]
        public StripeCreditCardOptions Card { get; set; }
```

I was then successfully creating a card StripeSource.

StripeSourceService().Create(), upon success, returns a StripeSource. In here, is a [StripeCard](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Entities/StripeCard.cs) object and in [StripeCard](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Entities/StripeCard.cs) is the ThreeDSecure property. However, it's currently set to Dictionary<string, string> whereas it is in fact a plain string when returned from Stripe (upon source creation). So this lead to modification number 2:

[entities\stripecard.cs](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Entities/StripeCard.cs) change the ThreeDSecure property to string

```
        [JsonProperty("three_d_secure")]
        public string ThreeDSecure { get; set; }
```

All good. Now, after creating the source, I can check the source.Card.ThreeDSecure property to see if 3DSecure is required, optional, or not_supported and process the transaction accordingly.

Now, once the user has been through the 3DSecure iFrame, Stripe will send a GET request back to whichever ReturnUrl you defined in the Stripe3DSecureCreateOptions model. Not quite normal for 3DSecure (normally they POST back), but I can handle that.

The key value they send back using GET is the id (string). They also send an authenticated boolean, error_code string and status string which can be useful.

So now, the next step, pretty simple now - take payment. You need to create a new StripeChargeCreateOptions() object, set the transaction amount, currency and set the SourceTokenOrExistingSourceId property to the id that Stripe sent back to your ReturnUrl.

Now you can create a new StripeChargeService() object and use .Create() with your StripeChargeCreateOptions object to finally take the payment.

Howevever, this leads on to another issue. When you call Create(), the StripeCharge object that's returned contains a Source object which has a StripeCard object in which is our ThreeDSecure property that we changed to string earlier. Only this time, Stripe sends back an array. This leads to modification number 3:

[entities\stripecard.cs](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Entities/StripeCard.cs) add a new custom JsonConverter to handle the array object:

```
        [JsonProperty("three_d_secure")]
        [JsonConverter(typeof(ThreeDSecureConverter))]
        public string ThreeDSecure { get; set; }
```

NEW FILE: Infrastructure\JsonConverters\ThreeDSecureConverter.cs:

```
    internal class ThreeDSecureConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return (objectType == typeof(Dictionary<string, string>));
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            JToken token = JToken.Load(reader);

            if(token.Type == JTokenType.Array)
            {
                return token.ToObject<Dictionary<string, string>>();
            }

            if(token.Type == JTokenType.String)
            {
                return token.ToString();
            }

            return null;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            serializer.Serialize(writer, value);
        }
    }
```

And there you have it. Payment is now taken using 3DSecure if the card requires it.

**Comment by jaymedavis** [comment] 2017-05-30 18:10
Thanks @sortit-craig for all the info! This is related to #857. I believe the issue here is Stripe should return the same `string` for 3D secure everywhere, instead of the array. Your solution works, but unless I'm misunderstanding this, it's really just a workaround to a bug. 

I think the fix is to change ```StripeCard``` to a string, and Stripe needs to update all 3D secure responses to be a string. 

cc @remi-stripe

**Comment by cwn00** [comment] 2017-05-30 18:45
Hi Jayme,

Yep, you're right, this is a workaround and does feel a bit hack-ish!

That should do the trick, if Stripe's responses were all string.

Craig.

**Comment by jaymedavis** [comment] 2017-05-31 17:38
this is fixed and will go live with the next build. it turned out to be a setting on my stripe testing account when i was in the beta program for 3dsecure - haha. easy enough to fix - just needed to be changed to a string!

**Comment by simonbladon** [comment] 2017-06-16 12:27
Hi Jayme,

Is this still an ongoing issue? I'm trying to complete the 3D secure charge using my tdsrc_ (as in the return_url data) but I'm getting "Unexpected character encountered while parsing value: {. Path 'three_d_secure', line 24, position 21." as a NewtonJson error

I have the latest Stripe.net nuget and I'm using my Stripe Test apis

Many thanks
Simon

**Comment by jaymedavis** [comment] 2017-06-16 12:31
Can you check fiddler and see what the response is coming back as? If you could also paste your code so I know which section you're in, that would help.

**Comment by simonbladon** [comment] 2017-06-16 13:01
This is the response back from Stripe (TDS) to my redirect_url page

GET /Stripe_IFrameContents.aspx?authenticated=true&id=tdsrc_Ar1toO82gDXIXj&status=succeeded&tds=tok_1AVJpeHAfin1pWIqrb0nSjMb HTTP/1.1

I'm then invoking the ChargeService.Create() with the following

var myCharge = new StripeChargeCreateOptions
{
	Amount = amount,
	Currency = currency,
	Description = description,
	SourceTokenOrExistingSourceId = tokenId, // id=tdsrc_Ar1toO82gDXIXj
	Metadata = metaData,
	Capture = capture
};
var chargeService = new StripeChargeService(GetStripeApiKey());
var stripeCharge = chargeService.Create(myCharge);
return stripeCharge;

The response back is an immediate exception error

Unexpected character encountered while parsing value: {. Path 'three_d_secure', line 24, position 21.

I've checked the Stripe API Log and the charge.suceeded log has the following

**Comment by simonbladon** [comment] 2017-06-16 13:03
"object": {
    "id": "ch_1AVJr3HAfin1pWIqj8Vu8tTo",
    "object": "charge",
	...
"source": {
      "id": "card_1AVJpeHAfin1pWIq1Bnp5Wjn",
      "object": "card",
	...
      "brand": "Visa",
      "country": "US",
      "customer": null,
      "cvc_check": "pass",
      "dynamic_last4": null,
      "exp_month": 9,
      "exp_year": 2024,
      "fingerprint": "W6KmLLOLQfvAQ2dt",
      "funding": "credit",
      "last4": "3063",
      "metadata": {
      },
      ...
      "three_d_secure": {
        "status": "succeeded",
        "authenticated": true
      },
      "tokenization_method": null
    },
	...

**Comment by jaymedavis** [comment] 2017-06-16 14:01
@remi-stripe looks like 3D secure isn't just a string in this case - is this authenticated property new?

**Comment by jaymedavis** [comment] 2017-06-17 18:10
Hi @simonbladon - it looks like you are using the 3D Secure service. This service is obsolete (and needs to be marked as such), so [here's a test](https://github.com/jaymedavis/stripe.net/blob/ee09a43044c6bf64f6baa04d49ed32252ffb3ca5/src/Stripe.Tests.XUnit/sources/creating_three_d_secure_source.cs) to show you how to use the service.

The "Card" property is not available in the master release yet, but you shouldn't need that anyway seeing as the card should come from a client-side token.

Let me know if this clears everything up for you!

**Closed by jaymedavis** 2017-06-17 18:10 UTC

**Comment by simonbladon** [comment] 2017-06-19 11:03
Hi @jaymedavis, thanks. I've recoded to use Source object. The 3DS redirect url is now a GET, rather than a POSTable address? (I'm using an iFrame to redirect the customer).

I got {
  "error": {
    "code": "url_not_found",
    "type": "invalid_request_error",
    "message": "Requested URL not found"
  }
}
Returned by my POST request. Is this now by design? Should the Redirect be a GET? or have I missed a step to change the redirection model?

**Comment by jaymedavis** [comment] 2017-06-19 11:19
Yes, it's a GET

**Comment by simonbladon** [comment] 2017-06-19 11:25
Is there a definitive list of returned parameters?

I was querying the following

"authenticated"
"id"
"status"
"tds"
"error_code"

returned to the "return_url" from the 3DSecure page

**Comment by renjithr2081** [comment] 2017-09-26 21:40
Hello , 

I just now upgraded to Stripe.net 10.4.0.0 , and getting the same error
Unexpected character encountered while parsing value: {. Path 'three_d_secure', line 24, position 21.

Was using old version 2.8.0 and all of a sudden was getting error "Unable to connect to remote server" on using chargeService.Create for each transaction.
But works well on 2nd time when the customer tries

So Stripe support asked me to upgrade the Library and using TSL1.2

We are in LIVE now so its affecting our customers.

**Comment by renjithr2081** [comment] 2018-03-13 01:12
Hello , 

Any update on this issue , I still face this issue.

**Comment by renjithr2081** [comment] 2018-06-03 07:40
Any updates on the issue??
As the date is nearby to upgrade the API I am giving another try..

The scenario is the same as explained by sortit-craig 
The Charge is created but the response object something is wrong.

[error.txt](https://github.com/stripe/stripe-dotnet/files/2065756/error.txt)

Attaching the complete error I get after calling , chargeService.Create(myCharge);

Please help
